linters:
  enable:
    - thelper
    - gofumpt
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - revive
    - forbidigo

linters-settings:
  forbidigo:
    forbid:
      - 'ioutil\.*'
