language: go
go: 1.8
sudo: true
install: make setup
script:
  - make test
after_success:
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken="$COVERALLS_TOKEN"
  - test -n "$TRAVIS_TAG" && gem install fpm && go run main.go
notifications:
  email: false
