language: go
go: 1.7.4
install: make setup
script:
  - make ci
after_success:
  - test -n "$TRAVIS_TAG" && gem install fpm
  - git status -sb
  - test -n "$TRAVIS_TAG" && go run main.go
  - git status -sb
notifications:
  email: false
