name: docs

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/htmltest.yml'
      - 'www/*'
  pull_request: {}

jobs:
  htmltest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: task docs:build
      - uses: wjdp/htmltest-action@master
        with:
          path: www/site
          config: www/htmltest.yml
